format = """
$username\
$hostname\
$directory\
${custom.jj}\
$cmd_duration\
$line_break\
$python\
$jobs\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
disabled = false
format = "[$branch]($style) "
style = "bright-black"

[git_status]
disabled = true
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[jobs]
symbol = "+"
threshold = 1
format = "[$symbol$number]($style) "
style = "bold blue"

[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [".jj"]
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
  )
'
'''

[custom.jjstate]
detect_folders = [".jj"]
command = '''
jj log --ignore-working-copy -r@ -l1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" " ${1}m ${2}+ ${3}-" | sd " 0." ""
'''

[custom.git_branch]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_branch"
description = "Only show git branch when not in a jj repo"
