format = """
$username\
$hostname\
$directory\
$git_commit\
$cmd_duration\
$line_break\
$python\
$jobs\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
disabled = true

[git_status]
disabled = true

[git_state]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[jobs]
symbol = "+"
threshold = 1
format = "[$symbol$number]($style) "
style = "bold blue"

[git_commit]
format = "[$hash]($style) "
style = "purple"
only_detached = false
