format = """
$username\
$hostname\
$directory\
${custom.jj}\
$cmd_duration\
$line_break\
$python\
$jobs\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
disabled = true
format = "[$branch]($style) "
style = "#5a5a5a"

[git_status]
disabled = true

[git_state]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[jobs]
symbol = "+"
threshold = 1
format = "[$symbol$number]($style) "
style = "bold blue"

[git_commit]
disabled = true
format = "[$hash]($style) "
style = "#5a5a5a"
only_detached = true
commit_hash_length = 7

[custom.jj]
detect_folders = [".jj"]
style = "#5a5a5a"
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
  )
'
'''
