local Color, c, Group, g, s = require 'colorbuddy'.setup()

Color.new('peach', '#FFE6B3')
Color.new('heavy_metal', '#21231F')
Color.new('nevada', '#616c72')
Color.new('half_baked', '#92bfce')
Color.new('beaver', '#9a8865')
Color.new('viridian', '#3c7768')
Color.new('chestnut_rose', '#d16161')
Color.new('feijoa', '#a5d48c')
Color.new('pine_glade', '#a8ce93')
Color.new('roman', '#d65c5c')
Color.new('jungle_mist', '#c5d4dd')
Color.new('chenin', '#ddd668')
Color.new('limed_spruce', '#3c4c55')
Color.new('corn', '#edc202')
Color.new('egg_white', '#ffebc3')
Color.new('asparagus', '#8eaf6b')
Color.new('japonica', '#db6c6c')
Color.new('amber', '#ffbf00')
Color.new('fuchsia_pink', '#c270c2')
Color.new('black_coral_pearl', '#4c5866')

Group.new('Normal', c.peach, c.heavy_metal)
Group.new('Comment', c.nevada)
Group.new('Special', c.half_baked, nil)
Group.new('Statement', c.beaver)
Group.new('Type', c.viridian)
Group.new('Function', c.chestnut_rose)
Group.new('PreProc', c.beaver)

Group.new('Identifier', c.feijoa)
Group.new('Constant', c.pine_glade)
Group.new('Boolean', c.roman)
Group.new('String', c.half_baked)
Group.new('Character', g.String)
Group.new('Number', g.Constant)
Group.new('Title', c.jungle_mist)

Group.new('LineNr', c.nevada)
Group.new('CursorLineNr', c.chenin)
Group.new('MatchParen', c.half_baked)
Group.new('Conceal', c.nevada)
Group.new('SpecialKey', c.nevada)
Group.new('ColorColumn', nil, c.nevada)
Group.new('SignColumn', nil, c.nevada)
Group.new('Folded', c.half_baked)
Group.new('FoldColumn', g.Folded)

Group.new('Directory', c.beaver)
Group.new('Underlined', nil, nil, s.underline)

Group.new('Visual', c.limed_spruce, c.half_baked)
Group.new('VisualNOS', nil, nil, s.underline)
Group.new('IncSearch', c.limed_spruce, c.corn)
Group.new('Search', g.IncSearch, c.chenin)

Group.new('StatusLine', c.egg_white, c.nevada)
Group.new('StatusLineNC', g.StatusLine, g.StatusLine)
Group.new('VertSplit', nil, c.nevada)
Group.new('WildMenu', c.nevada, c.egg_white)
Group.new('ModeMsg', c.half_baked)

Group.new('DiffAdd', c.limed_spruce, c.asparagus)
Group.new('DiffDelete', c.limed_spruce, c.japonica)
Group.new('DiffChange', c.amber, c.limed_spruce, s.underline)
Group.new('DiffText', c.limed_spruce, c.amber)

Group.new('Pmenu', c.egg_white, c.nevada)
Group.new('PmenuSel', c.egg_white, c.nevada, s.reverse)
Group.new('PmenuSbar', c.nevada)
Group.new('PmenuThumb', c.egg_white)

Group.new('ErrorMsg', c.nevada, c.japonica)
Group.new('WarningMsg', c.japonica)
Group.new('MoreMsg', c.half_baked)
Group.new('Question', c.half_baked)

Group.new('TabLine', c.egg_white, c.nevada)
Group.new('TabLineSel', c.egg_white, c.nevada, s.reverse)
Group.new('TabLineFill', nil, c.nevada)

Group.new('Error', c.japonica, nil, s.reverse)
Group.new('Ignore', nil, nil, nil)
Group.new('Todo', c.fuchsia_pink, nil, s.underline)

Group.new('NonText', c.nevada)

Group.new('Cursor', nil, c.egg_white)
Group.new('CursorColumn', nil, c.black_coral_pearl)
Group.new('CursorLine', nil, c.black_coral_pearl)

Group.new('Conditional', g.Statement, g.Statement, g.Statement)
Group.new('Debug', g.Special, g.Special, g.Special)
Group.new('Define', g.PreProc, g.PreProc, g.PreProc)
Group.new('Delimiter', g.Special, g.Special, g.Special)
Group.new('Exception', g.Statement, g.Statement, g.Statement)
Group.new('Float', g.Number, g.Number, g.Number)
Group.new('HelpCommand', g.Statement, g.Statement, g.Statement)
Group.new('HelpExample', g.Statement, g.Statement, g.Statement)
Group.new('Include', g.PreProc, g.PreProc, g.PreProc)
Group.new('Keyword', g.Statement, g.Statement, g.Statement)
Group.new('Label', g.Statement, g.Statement, g.Statement)
Group.new('Macro', g.PreProc, g.PreProc, g.PreProc)
Group.new('Operator', g.PreProc, g.PreProc, g.PreProc)
Group.new('PreCondit', g.PreProc, g.PreProc, g.PreProc)
Group.new('Repeat', g.Statement, g.Statement, g.Statement)
Group.new('SpecialChar', g.Special, g.Special, g.Special)
Group.new('SpecialComment', g.Special, g.Special, g.Special)
Group.new('StorageClass', g.Type, g.Type, g.Type)
Group.new('Structure', g.Type, g.Type, g.Type)
Group.new('Tag', g.Special, g.Special, g.Special)
Group.new('Typedef', g.Type, g.Type, g.Type)
