local Color, c, Group, g, s = require 'colorbuddy'.setup()

Color.new('black', '#282c34')
Color.new('light_black', '#2c323c')
Color.new('dark_grey', '#3e4452')
Color.new('grey', '#55606d')
Color.new('light_grey', '#abb2bf')
Color.new('white', '#d6e9ff')

Color.new('light_red', '#e06c75')
Color.new('dark_red', '#af5f5f')
Color.new('orange', '#FF875F')
Color.new('green', '#87af87')
Color.new('aqua', '#5fafaf')
Color.new('blue', '#6E88A6')
Color.new('purple', '#D18EC2')
Color.new('dark_purple', '#875faf')
Color.new('beige', '#D7AFAF')

local no = s.NONE
local re = s.reverse
local bo = s.bold
local un = s.underline
local unbo = un + bo

Group.new('Normal', c.light_grey, c.black, no)
Group.new('Visual', c.blue, c.black, re)

Group.new('Cursor', c.black, c.light_grey, no)
Group.new('CursorLine', nil, c.light_black, no)
Group.new('CursorColumn', nil, c.light_black, no)
Group.new('CursorLineNr', c.aqua, c.light_black, no)
Group.new('ColorColumn', nil, nil, no)
Group.new('Conceal', nil, nil, no)

Group.new('LineNr', c.grey, c.black, no)
Group.new('FoldColumn', c.light_grey, c.black, no)
Group.new('Folded', c.light_grey, c.black, no)
Group.new('MatchParen', c.grey, c.aqua, re)

Group.new('SignColumn', c.light_grey, c.black, no)
Group.new('NonText', c.dark_grey, nil, no)

Group.new('Pmenu', c.light_grey, c.dark_grey, no)
Group.new('PmenuSel', c.black, c.aqua, no)
Group.new('PmenuSbar', nil, c.grey, no)
Group.new('PmenuThumb', c.blue, c.beige, no)

Group.new('DiffChange', c.dark_purple, c.black, re)
Group.new('DiffText', c.orange, c.black, re)
Group.new('DiffDelete', c.dark_red, c.black, re)
Group.new('DiffAdd', c.green, c.black, re)

Group.new('GitGutterAdd', c.green, c.black, no)
Group.new('GitSignsAdd', g.GitGutterAdd, g.GitGutterAdd, g.GitGutterAdd)
Group.new('GitGutterChange', c.dark_purple, c.black, no)
Group.new('GitSignsChange', g.GitGutterChange, g.GitGutterChange, g.GitGutterChange)
Group.new('GitGutterDelete', c.dark_red, c.black, no)
Group.new('GitSignsDelete', g.GitGutterDelete, g.GitGutterDelete, g.GitGutterDelete)
Group.new('GitSignsCurrentLineBlame', g.NonText)

Group.new('Error', c.light_red, nil, re)
Group.new('ErrorMsg', c.black, c.light_red, no)
Group.new('WarningMsg', c.black, c.light_red, no)

Group.new('MoreMsg', c.grey, c.black, no)
Group.new('ModeMsg', c.black, c.green, no)
Group.new('Question', c.green, c.black, no)

Group.new('TabLine', c.blue, c.dark_grey, un)
Group.new('TabLineSel', c.black, c.blue, bo)
Group.new('TabLineFill', c.dark_grey, c.dark_grey, no)

Group.new('StatusLine', c.black, c.blue, no)
Group.new('StatusLineNC', c.black, c.grey, no)
Group.new('StatusLineTerm', c.black, c.blue, no)
Group.new('StatusLineTermNC', c.black, c.grey, no)

Group.new('VertSplit', c.dark_grey, c.dark_grey, no)
Group.new('WildMenu', c.black, c.orange, no)

Group.new('IncSearch', c.black, c.dark_red, unbo)
Group.new('Search', c.black, c.aqua, unbo)

Group.new('Comment', c.grey, nil, no)
Group.new('Constant', c.orange, c.black, no)
Group.new('Identifier', c.blue, c.black, no)
Group.new('Function', c.beige, c.black, no)
Group.new('Ignore', nil, nil, no)
Group.new('PreProc', c.aqua, c.black, no)
Group.new('Special', c.green, c.black, no)
Group.new('Statement', c.dark_red, c.black, no)
Group.new('String', c.green, c.black, no)
Group.new('Todo', c.purple, c.black, re)
Group.new('Type', c.dark_purple, c.black, no)
Group.new('StorageClass', c.light_red, c.black, no)
Group.new('TypeDef', c.purple, c.black, no)
Group.new('Underlined', c.aqua, c.black, un)
Group.new('SpecialKey', c.grey, c.black, no)
Group.new('Title', c.white, c.black, no)

Group.new('netrwDir', c.blue, c.black, no)

Group.new('Boolean', g.Constant, g.Constant, g.Constant)
Group.new('Character', g.Constant, g.Constant, g.Constant)
Group.new('Conditional', g.Statement, g.Statement, g.Statement)
Group.new('Debug', g.Special, g.Special, g.Special)
Group.new('Define', g.PreProc, g.PreProc, g.PreProc)
Group.new('Delimiter', g.Special, g.Special, g.Special)
Group.new('Exception', g.Statement, g.Statement, g.Statement)
Group.new('Float', g.Number, g.Number, g.Number)
Group.new('Include', g.PreProc, g.PreProc, g.PreProc)
Group.new('Keyword', g.Statement, g.Statement, g.Statement)
Group.new('Label', g.Statement, g.Statement, g.Statement)
Group.new('Macro', g.PreProc, g.PreProc, g.PreProc)
Group.new('Number', g.Constant, g.Constant, g.Constant)
Group.new('Operator', g.Statement, g.Statement, g.Statement)
Group.new('PreCondit', g.PreProc, g.PreProc, g.PreProc)
Group.new('Repeat', g.Statement, g.Statement, g.Statement)
Group.new('SpecialChar', g.Special, g.Special, g.Special)
Group.new('SpecialComment', g.Special, g.Special, g.Special)
Group.new('Structure', g.Type, g.Type, g.Type)
Group.new('Tag', g.Special, g.Special, g.Special)
Group.new('Terminal', g.Normal, g.Normal, g.Normal)
Group.new('Directory', g.Function, g.Function, g.Function)
