notify = ["/Users/gmurray/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-5.5"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
approvals_reviewer = "auto_review"
approval_policy = "on-request"

[projects."/Users/gmurray"]
trust_level = "trusted"

[projects."/Users/gmurray/.codex"]
trust_level = "trusted"

[projects."/Users/gmurray/Developer/idpair-central"]
trust_level = "trusted"

[projects."/Users/gmurray/Developer/ma_casino_api"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/i-keep-getting-this-error-in"]
trust_level = "trusted"

[projects."/Users/gmurray/Developer/nvsep"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/update-the-global-agents-md-file"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/find-the-automation-in-codex-backup"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/how-do-you-deactivate-a-user"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/i-need-to-deprovision-the-user"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/how-can-i-make-it-so"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/how-do-i-disable-a-user"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/chrome-plugin-chrome-openai-bundled-use"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-01/files-mentioned-by-the-user-agents"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/i-want-to-start-migrating-my"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/i-want-to-create-a-new"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-the-nvsep-aws-profile-and"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-chrome-plugin-chrome-openai-bundled"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-the-nvsep-aws-profile-and-2"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-the-aws-cli-with-nvsep"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-chrome-plugin-chrome-openai-bundled-2"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/use-chrome-plugin-chrome-openai-bundled-3"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/v1-plan-launchpad-summary-build-launchpad"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/look-up-the-new-aws-storage"]
trust_level = "trusted"

[projects."/Users/gmurray/Developer/infra-basecamp"]
trust_level = "trusted"

[projects."/Users/gmurray/Developer/launchpad"]
trust_level = "trusted"

[projects."/Users/gmurray/Documents/Codex/2026-06-02/update-codex-agents-md-to-add"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-06-02T19:27:46Z"
source_type = "local"
source = "/Users/gmurray/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-01T20:01:49Z"
source_type = "local"
source = "/Users/gmurray/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."github@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."sentry@openai-curated"]
enabled = true

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[features]
terminal_resize_reflow = true
memories = true
js_repl = false
prevent_idle_sleep = true

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
keepRemoteControlAwakeWhilePluggedIn = true
preventSleepWhileRunning = true
reviewDelivery = "detached"
hotkey-window-projectless-default-enabled = true
appearanceLightCodeThemeId = "codex"
appearanceDarkCodeThemeId = "codex"
followUpQueueMode = "steer"

[desktop.appearanceLightChromeTheme]
accent = "#0169cc"
contrast = 45
ink = "#0d0d0d"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = '"Maple Mono NF"'

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#751ed9"

[desktop.appearanceDarkChromeTheme]
accent = "#0169cc"
contrast = 60
ink = "#fcfcfc"
opaqueWindows = false
surface = "#111111"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"Maple Mono NF"'

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#b06dff"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/gmurray/Developer/nvsep" = "zed"

[memories]
generate_memories = true
use_memories = true

[mcp_servers.vanta_mcp]
enabled = true
url = "https://mcp.vanta.com/mcp"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/gmurray/.codex"
CODEX_HOME = "/Users/gmurray/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "4b6bfaf4ed2ce9b5cd68e60a61642eb4927a36306ba8c8993f6058607b3530fb"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"
