[colors.primary]
background = '#252623'
foreground = '#f1e9d2'

[colors.normal]
black = '#1c1e1b'
red = '#e75a7c'
green = '#8fb573'
yellow = '#dbb671'
blue = '#57a5e5'
magenta = '#aaaaff'
cyan = '#70c2be'
white = '#f1e9d2'

[colors.bright]
black = '#5b5e5a'
red = '#e75a7c'
green = '#8fb573'
yellow = '#dbb671'
blue = '#57a5e5'
magenta = '#aaaaff'
cyan = '#70c2be'
white = '#fff8f0'
