[".zsh/fast-syntax-highlighting"]
type = "archive"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/refs/heads/master.zip"
stripComponents = 1
refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip"
stripComponents = 1
refreshPeriod = "168h"

[".zsh/completion.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/completion.zsh"
refreshPeriod = "168h"

[".zsh/key-bindings.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/key-bindings.zsh"
refreshPeriod = "168h"

[".zsh/history.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/history.zsh"
refreshPeriod = "168h"

# [".config/helix/runtime"]
# type = "archive"
# url = "https://github.com/helix-editor/helix/archive/refs/heads/master.zip"
# stripComponents = 2
# include = ["runtime/**"]
# refreshPeriod = "168h"
