[".zsh/fast-syntax-highlighting"]
type = "archive"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/refs/heads/master.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"
