[".zsh/completion.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/lib/completion.zsh"
refreshPeriod = "168h"

[".zsh/history.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/lib/history.zsh"
refreshPeriod = "168h"

[".zsh/git-completion.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-completion.zsh"
refreshPeriod = "168h"

[".zsh/dotenv.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/dotenv/dotenv.plugin.zsh"
refreshPeriod = "168h"

[".zsh/brew.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/brew/brew.plugin.zsh"
refreshPeriod = "168h"

[".zsh/bun.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/bun/bun.plugin.zsh"
refreshPeriod = "168h"

[".zsh/chezmoi.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/chezmoi/chezmoi.plugin.zsh"
refreshPeriod = "168h"

[".zsh/fzf.plugin.zsh"]
type ="file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/fzf/fzf.plugin.zsh"
refreshPeriod = "168h"

[".zsh/gh.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/gh/gh.plugin.zsh"
refreshPeriod = "168h"

[".zsh/history.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/history/history.plugin.zsh"
refreshPeriod = "168h"

[".zsh/jj.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/jj/jj.plugin.zsh"
refreshPeriod = "168h"

[".zsh/mise.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/mise/mise.plugin.zsh"
refreshPeriod = "168h"

[".zsh/zoxide.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/zoxide/zoxide.plugin.zsh"
refreshPeriod = "168h"

[".zsh/fast-syntax-highlighting"]
type = "archive"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/refs/heads/master.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"
