[".zsh/fast-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"

[".zsh/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"

[".zsh/completion.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/completion.zsh"
refreshPeriod = "168h"

[".zsh/key-bindings.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/key-bindings.zsh"
refreshPeriod = "168h"

[".zsh/history.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/history.zsh"
refreshPeriod = "168h"

[".config/kitty/themes/poimandres.conf"]
type = "file"
url = "https://raw.githubusercontent.com/ubmit/poimandres-kitty/refs/heads/main/theme/poimandres.conf"
refreshPeriod = "168h"
