gui:
  theme:
    activeBorderColor:
      - '#eb6f92'
      - bold
    inactiveBorderColor:
      - '#6e6a86'
    optionsTextColor:
      - '#3e8fb0'
    selectedLineBgColor:
      - '#44415a'
    cherryPickedCommitBgColor:
      - '#f6c177'
    cherryPickedCommitFgColor:
      - '#232136'
    unstagedChangesColor:
      - '#eb6f92'
    defaultFgColor:
      - '#e0def4'
    searchingActiveBorderColor:
      - '#f6c177'
    selectedRangeBgColor:
      - '#44415a'
    selectedRangeFgColor:
      - '#e0def4'

  authorColors:
    '*': '#7287fd'
os:
  editInTerminal: true
