gui:
  theme:
    activeBorderColor:
      - "#b4befe"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#b4befe"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
  searchingActiveBorderColor:
    - "#f9e2af"

  authorColors:
    "*": "#b4befe"

  nerdFontsVersion: "3"
os:
  edit: "surf-next --wait {{filename}}"
  editAtLine: "surf-next --wait --goto {{filename}}:{{line}}"
  editAtLineAndWait: "surf-next --wait --goto {{filename}}:{{line}}"
  editInTerminal: true
  openDirInEditor: "surf-next --wait {{dir}}"
