--when.repositories = ["/Users/gamurray/Developer", "/Users/gamurray/go/src/github.com"]

[user]
name = "Gary Murray"
email = "gamurray@fanatics.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_rsa_gamurray.pub"

