local Color, c, Group, g, s = require('colorbuddy').setup()

local it = s.italic
local bo = s.bold
local rev = s.reverse
local un = s.underline
local unbo = bo + un

Color.new('base03', '#2d2d2d')
Color.new('base02', '#393939')
Color.new('base01', '#999999')
Color.new('base00', '#cccccc')
Color.new('base0', '#ebe4d3')
Color.new('base1', '#93a1a1')
Color.new('base2', '#eee8d5')
Color.new('base3', '#fdf6e3')
Color.new('yellow', '#fedb78')
Color.new('orange', '#f99157')
Color.new('red', '#f2777a')
Color.new('magenta', '#d567af')
Color.new('violet', '#cc99cc')
Color.new('blue', '#99cccc')
Color.new('cyan', '#d2fdfe')
Color.new('green', '#99cc99')

Group.new('Normal', c.base0, c.base03)
Group.new('Comment', c.base01, nil, it)
Group.new('Constant', c.cyan)
Group.new('Identifier', c.blue)
Group.new('Statement', c.green)
Group.new('PreProc', c.orange)
Group.new('Type', c.yellow)
Group.new('Special', c.red)
Group.new('Underlined', c.violet)
Group.new('Ignore', nil, nil)
Group.new('Error', c.red, nil, bo)
Group.new('Todo', c.magenta, nil, bo)

Group.new('SpecialKey', c.base00, c.base02, bo)
Group.new('NonText', c.base00, nil, bo)
Group.new('StatusLine', c.base02, c.base00)
Group.new('StatusLineNC', c.base03, c.base03)
Group.new('Visual', c.base01, c.base02)
Group.new('VisualNOS', g.Visual, g.Visual)
Group.new('Directory', c.blue)
Group.new('ErrorMsg', c.red, nil, rev)
Group.new('IncSearch', c.orange, nil, rev)
Group.new('Search', c.yellow, nil, rev)
Group.new('MoreMsg', c.blue)
Group.new('ModeMsg', c.blue)
Group.new('LineNr', c.base01, c.base02)
Group.new('Question', c.cyan, nil, bo)
Group.new('VertSplit', c.base02, nil)
Group.new('Title', c.orange, nil, bo)
Group.new('WarningMsg', c.red, nil, bo)
Group.new('WildMenu', c.base2, c.base02)
Group.new('Folded', c.base0, c.base02, unbo)
Group.new('FoldColumn', c.base0, c.base02)
Group.new('SignColumn', nil, c.base02)
Group.new('Conceal', c.blue)
Group.new('Pmenu', c.base0, c.base02)
Group.new('PmenuSel', c.base01, c.base2)
Group.new('PmenuSbar', c.base2, c.base0)
Group.new('PmenuThumb', c.base0, c.base03)
Group.new('TabLine', c.base0, c.base02)
Group.new('TabLineFill', g.TabLine, g.TabLine)
Group.new('TabLineSel', c.base01, c.base2, un)
Group.new('CursorColumn' , nil, c.base02)
Group.new('CursorLine', nil, c.base02)
Group.new('ColorColumn', nil, c.base02)
Group.new('Cursor', c.base03, c.base0)
Group.new('lCursor', g.Cursor, g.Cursor)
Group.new('MatchParen', c.red, c.base01, bo)

Group.new('DiffAdd', c.green, c.base02, bo)
Group.new('DiffChange', c.yellow, c.base02, bo)
Group.new('DiffDelete', c.red, c.base02, bo)
Group.new('DiffText', c.blue, c.base02, bo)

Group.new('LspDiagnosticsDefaultError', c.red)
Group.new('LspDiagnosticsUnderlineError', c.red, nil, un)
Group.new('LspDiagnosticsDefaultWarning', c.yellow)
Group.new('LspDiagnosticsDefaultInformation', c.blue)
Group.new('LspDiagnosticsDefaultHint', c.base01)
