local Color, c, Group, g, s = require('colorbuddy').setup()

Color.new('bg', '#282828')
Color.new('fg', '#fdf4c1')
Color.new('fg2', '#e9e0b2')
Color.new('fg3', '#d5cda2')
Color.new('fg4', '#c0b993')
Color.new('bg2', '#393939')
Color.new('bg3', '#4a4a4a')
Color.new('bg4', '#5c5c5c')
Color.new('keyword', '#dd6f48')
Color.new('builtin', '#fe8019')
Color.new('const',  '#bbaa97')
Color.new('comment', '#7c6f64')
Color.new('func', '#a89984')
Color.new('str', '#528b8b')
Color.new('type', '#66999d')
Color.new('var', '#83a598')
Color.new('warning', '#ff6523')
Color.new('warning2', '#ff2370')

Color.new('diffadd_fg', '#f8f8f8')
Color.new('diffadd_bg', '#46830c')

Color.new('diffdelete', '#ff0000')

Color.new('param', '#7aa697')
Color.new('number', '#e0819b')

Group.new('Normal', c.fg, c.bg)
Group.new('Cursor', c.bg, c.fg)
Group.new('Cursorline', nil, c.bg2)
Group.new('CursorColumn', nil, c.bg2)
Group.new('ColorColumn', nil, c.bg2)
Group.new('LineNr', c.fg2, c.bg2)
Group.new('VertSplit', c.fg3, c.bg3)
Group.new('MatchParen', c.warning2, nil, s.underline)
Group.new('StatusLine', c.fg2, c.bg3, s.bold)
Group.new('Pmenu', c.fg, c.bg2)
Group.new('PmenuSel',  nil, c.bg3)
Group.new('IncSearch', c.bg, c.keyword)
Group.new('Search', nil, nil, s.underline)
Group.new('Directory', c.const)
Group.new('Folded', c.fg4, c.bg)

Group.new('Boolean', c.const)
Group.new('Character', c.const)
Group.new('Comment', c.comment, nil, s.italic)
Group.new('Conditional', c.keyword)
Group.new('Constant', c.const)
Group.new('Define', c.keyword)
Group.new('DiffAdd', c.diffadd_fg, c.diffadd_bg, s.bold)
Group.new('DiffDelete', c.diffdelete)
Group.new('DiffChange', c.fg, c.var)
Group.new('DiffText', c.fg, c.builtin, s.bold)
Group.new('ErrorMsg', c.warning, c.bg2, s.bold)
Group.new('WarningMsg', c.fg, c.warning2)
Group.new('Float', c.number)
Group.new('Function', c.func)
Group.new('Identifier', c.type)
Group.new('Keyword', c.keyword, nil, s.bold)
Group.new('Label', c.var)
Group.new('NonText', c.bg4, c.bg2)
Group.new('Number', c.number)
Group.new('Operater', c.keyword)
Group.new('PreProc', c.keyword)
Group.new('Special', c.fg)
Group.new('SpecialKey', c.fg2, c.bg2)
Group.new('Statement', c.keyword)
Group.new('StorageClass', c.type)
Group.new('String', c.str)
Group.new('Tag', c.keyword)
Group.new('Title', c.fg, nil, s.bold)
Group.new('Todo', c.fg2, nil, s.reverse + s.bold)
Group.new('Type', c.type)
Group.new('Underlined', nil, nil, s.underline)
Group.new('Delimiter', c.fg)


Group.new('TSInclude', g.Keyword)
Group.new('TSVariable', c.var)
Group.new('TSVariableBuiltin', g.TSVariable)
Group.new('TSConstructor', c.var)
Group.new('TSParameter', c.param)
Group.new('TSProperty', c.param)
Group.new('TSTag', c.builtin)
Group.new('TSType', c.builtin)
Group.new('TSConstant', c.builtin)
