import = ["~/.config/alacritty/themes/kanagawa.toml"]

[scrolling]
history = 0

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "SemiBold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "SemiBold Italic" }
size = 16.0

[window]
option_as_alt = "Both"
