import = ["~/.config/alacritty/themes/kanagawa.toml"]

[scrolling]
history = 0

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Regular" }
bold = { family = "MonaspiceNe Nerd Font", style = "Bold" }
italic = { family = "MonaspiceRn Nerd Font", style = "Italic" }
bold_italic = { family = "MonaspiceRn Nerd Font", style = "Medium Italic" }
size = 14.0

[window]
option_as_alt = "Both"
