local Color, c, Group, g, s = require('colorbuddy').setup()

Color.new('base0', '#1b2b34')
Color.new('base1', '#343d46')
Color.new('base2', '#4f5b66')
Color.new('base3', '#65737e')
Color.new('base4', '#a7adba')
Color.new('base5', '#c0c5ce')
Color.new('base6', '#cdd3de')
Color.new('base7', '#d8dee9')

Color.new('red', '#ec5f67')
Color.new('orange', '#f99157')
Color.new('yellow', '#fac863')
Color.new('green', '#99c794')
Color.new('cyan', '#62b3b2')
Color.new('blue', '#6699cc')
Color.new('purple', '#c594c5')
Color.new('violet', '#c594c5')
Color.new('brown', '#ab7967')
Color.new('white', '#ffffff')

Group.new('Debug', c.red)
Group.new('Directory', c.blue)
Group.new('ErrorMsg', c.red, c.base0)
Group.new('Exception', c.red)
Group.new('FoldColumn', c.blue, c.base0)
Group.new('Folded', c.base3, c.base1)
Group.new('IncSearch', c.base1, c.orange)

Group.new('Macro', c.red)
Group.new('MatchParen', c.base5, c.base3)
Group.new('ModeMsg', c.green)
Group.new('MoreMsg', c.green)
Group.new('Question', c.blue)
Group.new('Search', c.base3, c.yellow)
Group.new('SpecialKey', c.base3)
Group.new('Underlined', c.red, nil, s.underline)
Group.new('Visual', nil, c.base2)
Group.new('VisualNOS', c.red)
Group.new('WarningMsg', c.red)
Group.new('WildMenu', c.base7, c.blue)
Group.new('Title', c.blue)
Group.new('Conceal', c.blue, c.base0)
Group.new('Cursor', c.base0, c.base5)
Group.new('NonText', c.base3)
Group.new('Normal', c.base7, c.base0)
Group.new('EndOfBuffer', c.base5, c.base0)
Group.new('LineNr', c.base3, c.base0)
Group.new('SignColumn', c.base0, c.base0)
Group.new('StatusLine', c.base1, c.base3)
Group.new('StatusLineNC', c.base0, c.base0)
Group.new('VertSplit', c.base0, c.base2)
Group.new('ColorColumn', nil, c.base1)
Group.new('CursorColumn', nil, c.base1)
Group.new('CursorLine', nil, c.base1)
Group.new('CursorLineNR', c.base0, c.base0)
Group.new('CursorLineNr', c.base3, c.base1)
Group.new('PMenu', c.base4, c.base1)
Group.new('PMenuSel', c.base7, c.blue)
Group.new('PmenuSbar', nil, c.base2)
Group.new('PmenuThumb', nil, c.base7)
Group.new('TabLine', c.base3, c.base1)
Group.new('TabLineFill', c.base3, c.base1)
Group.new('TabLineSel', c.green,  c.base1)

Group.new('Boolean', c.orange)
Group.new('Character', c.red)
Group.new('Comment', c.base3, nil, s.italic)
Group.new('Conditional', c.purple)
Group.new('Constant', c.orange)
Group.new('Define', c.purple)
Group.new('Delimiter', c.brown)
Group.new('Float', c.orange)
Group.new('Function', c.blue)

Group.new('Identifier', c.cyan)
Group.new('Include', c.blue)
Group.new('Keyword', c.purple)

Group.new('Label', c.yellow)
Group.new('Number', c.orange)
Group.new('Operator', c.base5)
Group.new('PreProc', c.yellow)
Group.new('Repeat', c.yellow)
Group.new('Special', c.cyan)
Group.new('SpecialChar', c.brown)
Group.new('Statement', c.red)
Group.new('StorageClass', c.yellow)
Group.new('String', c.green)
Group.new('Structure', c.purple)
Group.new('Tag', c.yellow)
Group.new('Todo', c.yellow, c.base1)
Group.new('Type', c.yellow)
Group.new('Typedef', c.yellow)

Group.new('LspDiagnosticsDefaultError', c.red)
Group.new('LspDiagnosticsSignError', c.red)

Group.new('LspDiagnosticsDefaultWarning', c.yellow)
Group.new('LspDiagnosticsSignWarning', c.yellow)

Group.new('LspDiagnosticsDefaultInformation', c.blue)
Group.new('LspDiagnosticsSignInformation', c.blue)

Group.new('LspDiagnosticsDefaultHint', c.cyan)
Group.new('LspDiagnosticsSignHint', c.cyan)

Group.new('TSInclude', c.cyan, nil, s.italic)
Group.new('TSPunctBracket', c.cyan)
Group.new('TSPunctDelimiter', c.base7)
Group.new('TSParameter', c.base7)
Group.new('TSType', c.blue)
Group.new('TSFunction', c.cyan)
Group.new('TSTagDelimiter', c.cyan)
Group.new('TSProperty', c.yellow)
Group.new('TSMethod', c.blue)
Group.new('TSParameter', c.yellow)
Group.new('TSConstructor', c.base7)
Group.new('TSVariable', c.base7)
Group.new('TSOperator', c.base7)
Group.new('TSTag', c.base7)
Group.new('TSKeyword', c.purple)
Group.new('TSKeywordOperator', c.purple)
Group.new('TSVariableBuiltin', c.red)
Group.new('TSLabel', c.cyan)

Group.new('DiffAdd', c.green, c.base1, s.bold)
Group.new('DiffChange', c.base3, c.base1)
Group.new('DiffDelete', c.red, c.base1)
Group.new('DiffText', c.blue, c.base1)
