theme = "catppuccin_mocha"

[editor]
line-number = "relative"
rulers = []
end-of-line-diagnostics = "hint"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
