theme = "opencode"

[editor]
line-number = "relative"
rulers = []
end-of-line-diagnostics = "hint"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

