theme = "gruvy"

[editor]
scroll-lines = 1
completion-trigger-len = 1
idle-timeout = 50
line-number = "relative"
true-color = true
color-modes = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right =  ["diagnostics", "version-control", "spacer", "selections", "position", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
X = "extend_line_above"
a = ["append_mode", "collapse_selection"]
space.w.c = ":buffer-close"
";" = ["repeat_last_motion"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "normal_mode"]
