[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]

[language-server.typescript-language-server.config]
hostInfo = "helix"
typescript.inlayHints.parameterNames.enabled = "literals"
typescript.inlayHints.parameterTypes.enabled = true
typescript.inlayHints.variableTypes.enabled = true
typescript.inlayHints.propertyDeclarationTypes.enabled = true
typescript.inlayHints.functionLikeReturnTypes.enabled = true
typescript.inlayHints.enumMemberValues.enabled = true
javascript.inlayHints.parameterNames.enabled = "literals"
javascript.inlayHints.parameterTypes.enabled = true
javascript.inlayHints.variableTypes.enabled = true
javascript.inlayHints.propertyDeclarationTypes.enabled = true
javascript.inlayHints.functionLikeReturnTypes.enabled = true
javascript.inlayHints.enumMemberValues.enabled = true
