return {
	{ "LuaSnip", enabled = false },
	{ "cmp_luasnip", enabled = false },
	{ "mini.pairs", enabled = false },
	{ "nvim-ts-context-commentstring", enabled = false },
	{ "neo-tree.nvim", enabled = false },
	{ "nvim-spectre", enabled = false },
	{ "flash.nvim", enabled = false },
	{ "todo-comments.nvim", enabled = false },
	{ "nvim-notify", enabled = false },
	{ "bufferline.nvim", enabled = false },
	{ "mini.indentscope", enabled = false },
	{ "noice.nvim", enabled = false },
	{ "nvim-dap", enabled = false },
	{ "nvim-dap-go", enabled = false },
	{ "neotest-go", enabled = false },
	{ "vim-illuminate", enabled = false },
}
