"ui.text" = "fg"
"ui.text.inactive" = "grey"
"ui.text.focus" = { fg = "bg0", bg = "bg_blue" }

"ui.background" = { bg = "bg0" }

"ui.linenr" = { fg = "grey", bg = "bg0" }
"ui.linenr.selected" = { fg = "fg", bg = "bg0" }

"ui.cursor" = { fg = "bg0", bg = "grey" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg" }
"ui.cursor.match" = { fg = "orange", bg = "grey", modifiers = ["bold"] }

"ui.statusline" = { fg = "fg", bg = "bg2" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "green", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "purple", modifiers = ["bold"] }

"ui.selection" = { bg = "bg3" }

"ui.menu" = { fg = "fg", bg = "bg1" }
"ui.menu.selected" = { fg = "bg0", bg = "bg_blue" }

"ui.help" = { fg = "fg", bg = "bg1" }

"ui.popup" = { fg = "fg", bg = "bg1" }
"ui.popup.info" = { fg = "fg", bg = "bg1" }

"ui.window" = "bg3"

"diff.plus" = "diff_add"
"diff.minus" = "diff_delete"
"diff.delta" = "diff_change"

error = "red"
hint = "purple"
info = "cyan"
warning = "yellow"

"diagnostic.error"= "red"
"diagnostic.hint"= "purple"
"diagnostic.info"= "cyan"
"diagnostic.warning"= "yellow"

annotation = "fg"
attribute = "cyan"
boolean = "orange"
character = "organge"
comment = { fg = "bg_yellow", modifiers = ["italic"] }
conditional = "purple"

constant = "organge"
"constant.builtin" = "orange"
"constant.macro" = "organge"

constructor = { fg = "yellow", modifiers = ["bold"] }
expection = "purple"
field = "cyan"
float = "orange"

function = "blue"
"function.builtin" = "orange"
"function.macro" = "cyan"

include = "purple"

keyword = "purple"
"keyword.function" = "purple"
"keyword.operator" = "purple"

label = "red"
method = "blue"
namespace = "yellow"
none = "fg"
number = "orange"
operator = "purple"

parameter = "red"
"parameter.reference" = "fg"

property = "cyan"

"punctuation.delimiter" = "light_grey"
"punctuation.bracket" = "light_grey"
"punctuation.special" = "red"

repeat = "purple"

string = "green"
"string.regex" = "orange"
"string.escape" = "red"

symbol = "cyan"

tag = "purple"
"tag.attribute" = "yellow"
"tag.delimiter" = "purple"

"text.uri" = { fg = "cyan", modifiers = ["underline"] }
"text.todo" = { fg = "black", bg = "purple" }
"text.note" = { fg = "black", bg = "blue" }
"text.danger" = { fg = "black", bg = "red" }
"text.warning" = { fg = "black", bg = "orange" }

note = "fg"
danger = "fg"

type = "yellow"
"type.builtin" = "orange"

variable = "fg"
"variable.builtin" = "red"
"variable.global" = "red"
"variable.static" = "orange"

[palette]
black = "#111210"
bg0 = "#252623"
bg1 = "#2f312c"
bg2 = "#383b35"
bg3 = "#3a3d37"
bg_d = "#1c1e1b"
bg_blue = "#68aee8"
bg_yellow = "#e2c792"
fg = "#f1e9d2"
purple = "#aaaaff"
green = "#8fb573"
orange = "#ff9966"
blue = "#57a5e5"
yellow = "#dbb671"
cyan = "#83b5d1"
red = "#e75a7c"
grey = "#5b5e5a"
light_grey = "#838781"
dark_cyan = "#2b5d63"
dark_red = "#833b3b"
dark_yellow = "#7c5c20"
dark_purple = "#79428a"
diff_add = "#8fb573"
diff_delete = "#e75a7c"
diff_change = "#57a5e5"
diff_text = "#595653"