"ui.menu" = {bg = "black"}
"ui.menu.selected" = {bg = "black_bright"}
"ui.menu.scroll" = {fg = "black", bg = "black"}
"ui.window" = "black"
"ui.linenr" = {fg = "black_bright"}
"ui.linenr.selected" = {fg = "white"}
"ui.popup" = {fg = "white", bg = "black"}
"ui.popup.info" = {fg = "white", bg = "none"}
"ui.selection" = {fg = "black", bg = "blue"}
"ui.selection.primary" = {modifiers = ["reversed"]}
"comment" = {fg = "black_bright"}
"ui.statusline" = {fg = "white", bg = "none"}
"ui.statusline.inactive" = {fg = "black", bg = "none"}
"ui.help" = {fg = "white", bg = "none"}
"ui.cursor" = {modifiers = ["reversed"]}
"ui.virtual.ruler" = {bg = "#1a1a1a"}
"ui.virtual.inlay-hint" = "black_bright"
"ui.virtual.inlay-hint.parameter" = "black_bright"
"ui.virtual.inlay-hint.type" = "black_bright"
"variable" = "white"
"variable.builtin" = "yellow"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "blue"
"type" = "cyan"
"ui.cursor.match" = {fg = "cyan", modifiers = ["underlined"]}
"ui.cursorline.primary" = {bg = "bg_bright"}
"ui.cursorline.secondary" = {bg = "bg_bright"}
"ui.highlight" = {bg = "black"}
"string" = "green"
"variable.other.member" = "blue"
"constant.character.escape" = "yellow"
"function" = "yellow"
"function.builtin" = "blue"
"function.method" = "blue"
"constructor" = "blue"
"special" = "yellow"
"keyword" = "magenta_bright"
"keyword.control.repeat" = "magenta"
"label" = "magenta"
"namespace" = "blue"
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"
"diagnostic" = {modifiers = ["underlined"]}
"ui.gutter" = {bg = "none"}
"info" = "blue"
"hint" = "white"
"debug" = "white"
"warning" = "yellow"
"error" = "red"
"ui.virtual.whitespace" = {fg = "black_bright"}
"markup.heading.marker" = "#00b2ff"
"markup.heading.1" = "#00b2ff"
"markup.heading.2" = "#00b2ff"
"markup.heading.3" = "#00b2ff"
"markup.heading.4" = "#00b2ff"
"markup.heading.5" = "#00b2ff"
"markup.heading.6" = "#00b2ff"
"markup.bold" = {modifiers = ["bold"]}
"markup.italic" = {modifiers = ["italic"]}
"markup.underline.link" = {fg = "#008a88", modifiers = ["underlined"]}
"markup.raw.inline" = {bg = "#303030", fg = "#ff4f58"}
"markup.list.unnumbered" = "black_bright"
"markup.list.numbered" = "black_bright"
"markup.raw.block" = {fg = "black_bright"}
"markup.link.url" = {fg = "#008a88", modifiers = ["underlined"]}
"markup.link.label" = {fg = "#00b255"}
"markup.link.text" = {fg = "#00b255"}

[palette]
"bg_bright" = "#202020"
"black" = "#282a2e"
"black_bright" = "#4B4B4B"
"white" = "#C5C8C6"
"blue" = "#8056FF"
"yellow" = "#D3E561"
"cyan" = "#04D7D7"
"green" = "#00D787"
"magenta" = "#ED61D7"
"magenta_bright" = "#FF7AEA"
"red" = "#D74E6F"
