inherits = "tokyonight_storm"

"ui.cursor.primary" = { bg = "foreground", fg = "background" }
"function" = { fg = "blue" }
"keyword" = { fg = "cyan" }
"keyword.function" = { fg = "magenta" }
"markup.italic" = { fg = "yellow" }

"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "teal" } }
