palette = 0=#3a3a3a
palette = 1=#f17471
palette = 2=#49c970
palette = 3=#f6c251
palette = 4=#7698fd
palette = 5=#edb2f1
palette = 6=#93e9f6
palette = 7=#aeaeae
palette = 8=#5c5c5c
palette = 9=#fc533a
palette = 10=#12c905
palette = 11=#fcd53a
palette = 12=#a2bcff
palette = 13=#f799c6
palette = 14=#65d9eb
palette = 15=#f1ece8
background = 1c1c1c
foreground = f1ece8
cursor-color = fab283
cursor-text = 1f1f1f
selection-background = 3a3a3a
selection-foreground = f1ece8
