unbind-key c-b
set-option -g prefix c-space

set-option -g base-index 0
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g repeat-time 500
set-option -g mouse on
set-option -ga terminal-overrides ",xterm-256color:Tc"

bind -n M-Left previous-window
bind -n M-Right next-window

bind v split-window -h
bind s split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind g new-window "lazygit"

bind-key x kill-pane

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set-option -g  default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=colour231,bg=colour31"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour254"
set -g status-style "none,bg=#2c3044"
set -g message-style "fg=colour231,bg=colour31"
set -g pane-border-style "fg=colour240"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=colour250,bg=#2c3044"
set -g status-left "#[fg=#1e1e20,bg=#80a0ff,bold] #S #[fg=#c3ccdb,bg=#2c3044,nobold] "
set -g status-right "#[fg=#c3ccdb,bg=#2c3044,nobold]|#[fg=#80a0fe,bg=#2c3044] %Y-%m-%d %H:%M "
setw -g window-status-format "#[fg=#282928,bg=#c6c6c6] #W #[fg=#2c3044,bg=#2c3044] "
setw -g window-status-current-format "#[fg=#282928,bg=#af80ff,bold] #W #[fg=#2c3044,bg=#2c3044] "

run -b '~/.tmux/plugins/tpm/tpm'
