[tools]
actionlint = "latest"
atuin = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bun = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "1.26.3"
imagemagick = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
ninja = "latest"
node = "latest"
pnpm = "latest"
protobuf = "latest"
pulumi = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
tmux = "latest"
uv = "latest"
worktrunk = "latest"
yazi = "latest"
zoxide = "latest"
