[tools]
actionlint = "latest"
atuin = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bun = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "1.26.3"
imagemagick = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
ninja = "latest"
node = "latest"
pnpm = "latest"
protobuf = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
worktrunk = "latest"
yazi = "latest"
zoxide = "latest"

[dotfiles]
"~/.zshrc" = { mode = "symlink" }
"~/.zshenv" = { mode = "symlink" }
"~/.codex/AGENTS.md" = "~/.dotfiles/.agents/AGENTS.md"
"~/.codex/browser/config.toml" = { mode = "symlink" }
"~/.codex/config.toml" = { mode = "symlink" }
"~/.codex/keybindings.json" = { mode = "symlink" }
"~/.codex/skills" = { mode = "symlink" }
"~/.config/nvim" = { mode = "symlink" }
"~/.config/starship.toml" = { mode = "symlink" }
"~/.gitconfig" = { mode = "symlink" }
"~/Library/Application Support/com.mitchellh.ghostty" = { mode = "symlink" }
"~/Library/Application Support/lazygit" = { mode = "symlink" }
"~/.config/mise/config.toml" = "~/.dotfiles/.config/mise/config.toml"
"~/.config/herdr" = { mode = "symlink" }
"~/.config/opencode" = { mode = "symlink" }
"~/.config/opencode/AGENTS.md" = "~/.dotfiles/.agents/AGENTS.md"
"~/.agents" = { mode = "symlink" }

[settings]
experimental = true
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.brew.taps]
"kitlangton/tap" = "https://github.com/kitlangton/homebrew-tap.git"
"modem-dev/tap" = "https://github.com/modem-dev/homebrew-tap.git"

[bootstrap.packages]
"brew:cmake" = "latest"
"brew:curl" = "latest"
"brew:gettext" = "latest"
"brew:gh" = "latest"
"brew:kitlangton/tap/ghui" = "latest"
"brew:git" = "latest"
"brew:glib" = "latest"
"brew:gnupg" = "latest"
"brew:modem-dev/tap/hunk" = "latest"
"brew:libpq" = "latest"
"brew:libyaml" = "latest"
"brew:ncurses" = "latest"
"brew:pdftk-java" = "latest"
"brew:pkgconf" = "latest"
"brew:poppler" = "latest"
"brew:tree" = "latest"
"brew:zsh-syntax-highlighting" = "latest"
